name: GitHub Action for textlint
description: Display textlint result on GitHub
author: yutailang0119

branding:
  icon: check-square
  color: white

inputs:
  report-path:
    description: The lint report file path.
    required: false
  textlint-output:
    description: The json format output by textlint
    required: false
  ignore-warnings:
    description: Ignore Lint Warnings
    default: 'false'

runs:
  using: node20
  main: dist/index.js
